### ISSUE TITLE
mail__design.mtt.php

### ISSUE THREAD

**Issue by garwinch** [bablukid/cagette#39]
salut, c'est encore moi, 

je suis en train de rentrer  produits et users dans cette formidable cagette ...mais pour lancer l'invitation user par mail j'ai : 

> Trying to get property of non-object (errno: 8) in /var/www/my_webapp__3/lang/fr/tmp/mail__design.mtt.php at line #20 

uncaught exception: There is no active transaction

> in file: /var/www/my_webapp__3/www/lib/php/db/_PDO/PDOConnection.class.php line 96
> #0 /var/www/my_webapp__3/www/lib/php/db/_PDO/PDOConnection.class.php(96): PDO->commit()
> #1 /var/www/my_webapp__3/www/lib/sys/db/Transaction.class.php(36): php_db__PDO_PDOConnection->commit()
> #2 /var/www/my_webapp__3/www/lib/sugoi/BaseApp.class.php(388): sys_db_Transaction::main(Object(php_db__PDO_PDOConnection), Array, Array)
> #3 /var/www/my_webapp__3/www/lib/sugoi/BaseApp.class.php(418): sugoi_BaseApp->run()
> #4 /var/www/my_webapp__3/www/lib/App.class.php(66): sugoi_BaseApp::main()
> #5 /var/www/my_webapp__3/www/index.php(9): App::main()
> #6 {main

}

Don voici la ligne  : 

`$this->buf .= _hxtemplo_string($ctx->group->name);`

Voilà, si tu peut m'aider à comprendre le contenu de cette ligne et trouver des pistes .. sans vouloir déranger  bien sur :-)

**Comment by tomdereub** [comment]
Salut,
J'ai le même souci pour l'envoi des mails, est-ce que quelqu'un a trouvé une solution ? Cagette est installé sur yunohost, en suivant la procédure de la doc.
Merci !
